backend = "xrender";
vsync = false;

#################################
# Shadows
#################################

shadow = true;
shadow-radius = 3;
shadow-opacity = 0.10;

#################################
# Fading
#################################

fading = true;
fade-delta = 6;

#################################
# Transparency
#################################

inactive-opacity = 1.0;
active-opacity = 1.0;

#################################
# Blur / corners OFF
#################################

blur-method = "none";
corner-radius = 0;
